// clipboard API のユニットテスト（issue #199）
//
// テスト対象: src-tauri/src/api/clipboard.rs
//   - SELF_COPY_TYPE 定数
//   - copy_text_to_clipboard コマンド
//
// ブラックボックス／ホワイトボックス テスト設計と、テスト対象外とする理由:
//
// `copy_text_to_clipboard` は `#[cfg(target_os = "macos")]` ブロック内で
// `AppHandle::run_on_main_thread` 経由で実際の NSPasteboard
// （`NSPasteboard::generalPasteboard()`、プロセス外・OS 全体で共有されるシステム
// リソース）に対して `clearContents` / `declareTypes_owner` / `setString_forType`
// を呼び出す。これをユニットテストで検証しようとすると、以下の理由で
// テストが困難、あるいは有害である:
//
//   1. `tauri::test::mock_app()` が返す `MockRuntime` はイベントループを
//      実際には駆動しないため、`run_on_main_thread` に登録したクロージャが
//      いつ・本当に実行されるかを保証できない
//      （`src-tauri/src/api/db_settings.rs` の `pick_db_file_path` も同様の
//      理由で既存テスト `tests/api/db_settings.rs` の対象外となっている）。
//   2. 実行できたとしても、テスト実行中のマシンの「本物の」システム
//      クリップボードを実際に書き換えてしまう副作用があり、CI 環境は
//      もちろん開発者のローカル環境でも実行中の作業（他アプリのクリップ
//      ボード内容）を破壊しかねず、テストとして不適切。
//   3. `tests/api/clipboard_monitor.rs` 冒頭コメントで明記されている方針
//      （NSPasteboard への実アクセスを伴うコードは CI 環境での安定性に
//      欠けるためテスト対象外とする）にも合致する。
//
// 以上の理由により `copy_text_to_clipboard` 自体（および macOS 専用ヘルパー
// `write_text_with_marker`、非 macOS 向けの `Err("Unsupported platform")`
// フォールバック分岐）はテスト対象外とする。
//
// 一方で `SELF_COPY_TYPE` 定数はテスト可能かつ重要な値である。この定数は
// `clipboard_monitor::skip_reason()` が「アプリ内コピーかどうか」を判定する
// 際の比較対象そのものであり、両モジュール間の契約（コピー時に書き込む
// UTI と、監視時に検知する UTI が完全一致すること）を保証する回帰テストとして
// 価値がある。値が変わると `skip_reason()` が SelfCopy を検知できなくなり、
// アプリ自身のコピー操作が誤って Clipboard History に記録されてしまう
// （issue #199 が解決しようとした問題がぶり返す）ため、明示的にテストする。

use app_lib::api::clipboard::SELF_COPY_TYPE;

/// SELF_COPY_TYPE はアプリ識別子（biz.nosetech.rightcheat）をベースにした
/// 逆ドメイン形式の文字列であること。
/// 一般的な UTI や他アプリの UTI と衝突しないための命名規則を満たしているかを
/// 確認する（同値分割: 有効クラス＝アプリ固有プレフィックスを持つ文字列）。
#[test]
fn self_copy_type_has_expected_value() {
    assert_eq!(SELF_COPY_TYPE, "biz.nosetech.rightcheat.self-copy");
}

/// SELF_COPY_TYPE が nspasteboard.org 規約の予約タイプ（org.nspasteboard.*）と
/// 衝突しないこと。`clipboard_monitor::skip_reason()` は
/// CONCEALED_TYPE / AUTO_GENERATED_TYPE / SELF_COPY_TYPE の3つを文字列比較で
/// 判定しており、値が重複すると異なる SkipReason バリアントが誤って
/// 選択されてしまうため、他の予約タイプと異なることを回帰的に保証する。
#[test]
fn self_copy_type_does_not_collide_with_nspasteboard_org_reserved_types() {
    const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
    const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

    assert_ne!(SELF_COPY_TYPE, CONCEALED_TYPE);
    assert_ne!(SELF_COPY_TYPE, AUTO_GENERATED_TYPE);
}

/// SELF_COPY_TYPE は空文字列ではないこと（境界値分析: 定数が意図せず空に
/// なっていないかの健全性チェック）。空文字列だと NSPasteboard の
/// `types()` 一覧に空文字列が含まれるだけの無意味な判定になってしまう。
#[test]
fn self_copy_type_is_not_empty() {
    assert!(!SELF_COPY_TYPE.is_empty());
}
