/// PoC: macOS clipboard change monitoring via NSPasteboard.changeCount polling.
///
/// This module is research code for issue #145.
/// It demonstrates that clipboard monitoring is feasible using only the existing
/// objc2-app-kit dependency with a background polling thread.
///
/// Key findings:
/// - No new dependencies required (objc2-app-kit already in project)
/// - NSPasteboard.changeCount is the industry-standard detection mechanism on macOS
/// - org.nspasteboard.ConcealedType check respects password manager "do not store" intent
/// - 500ms polling interval is used by most clipboard managers (Maccy, etc.)
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
use std::thread;
use std::time::Duration;

use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};

const POLL_INTERVAL_MS: u64 = 500;
const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// Minimum text length to record (matches Preferences default in the final spec).
const MIN_TEXT_LENGTH: usize = 2;

pub struct ClipboardMonitor {
    running: Arc<AtomicBool>,
}

impl ClipboardMonitor {
    pub fn new() -> Self {
        Self {
            running: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Start background polling. Safe to call once; subsequent calls are no-ops.
    pub fn start(&self) {
        if self.running.swap(true, Ordering::SeqCst) {
            return;
        }

        let running = Arc::clone(&self.running);
        thread::spawn(move || {
            log::info!(
                "[clipboard_monitor] Started polling (interval={}ms)",
                POLL_INTERVAL_MS
            );
            let mut last_change_count: isize = -1;

            while running.load(Ordering::SeqCst) {
                unsafe {
                    objc2::rc::autoreleasepool(|_| {
                        let pb = NSPasteboard::generalPasteboard();
                        let count = pb.changeCount();

                        if count != last_change_count {
                            if last_change_count != -1 {
                                on_clipboard_changed(&pb);
                            }
                            last_change_count = count;
                        }
                    });
                }
                thread::sleep(Duration::from_millis(POLL_INTERVAL_MS));
            }

            log::info!("[clipboard_monitor] Stopped polling");
        });
    }

    /// Stop the background thread gracefully.
    pub fn stop(&self) {
        self.running.store(false, Ordering::SeqCst);
    }
}

impl Default for ClipboardMonitor {
    fn default() -> Self {
        Self::new()
    }
}

/// Called when `changeCount` increases. Reads text and applies filters.
fn on_clipboard_changed(pb: &NSPasteboard) {
    if is_concealed_type(pb) {
        log::debug!("[clipboard_monitor] Skipped: concealed or auto-generated type");
        return;
    }

    let text = unsafe {
        pb.stringForType(NSPasteboardTypeString)
            .map(|s| s.to_string())
    };

    match text {
        None => {
            log::debug!("[clipboard_monitor] No text content on pasteboard");
        }
        Some(t) if t.chars().count() < MIN_TEXT_LENGTH => {
            log::debug!(
                "[clipboard_monitor] Skipped: text too short ({} chars)",
                t.chars().count()
            );
        }
        Some(t) => {
            // In the final implementation this would be persisted to the DB.
            log::info!(
                "[clipboard_monitor] Captured text ({} chars): {}",
                t.chars().count(),
                truncate_for_log(&t, 80)
            );
        }
    }
}

/// Returns true if the pasteboard contains a type that signals "do not record".
/// Respects the nspasteboard.org convention used by password managers.
fn is_concealed_type(pb: &NSPasteboard) -> bool {
    let Some(types) = (unsafe { pb.types() }) else {
        return false;
    };

    for i in 0..types.count() {
        let t_str = types.objectAtIndex(i).to_string();
        if t_str == CONCEALED_TYPE || t_str == AUTO_GENERATED_TYPE {
            return true;
        }
    }
    false
}

pub fn truncate_for_log(s: &str, max_chars: usize) -> String {
    let chars: Vec<char> = s.chars().collect();
    if chars.len() <= max_chars {
        s.to_string()
    } else {
        format!("{}…", chars[..max_chars].iter().collect::<String>())
    }
}
