//! macOS クリップボード監視（NSPasteboard.changeCount ポーリング）。
//!
//! macOS には他アプリのクリップボード変更をイベント通知する公式 API が存在しないため、
//! `NSPasteboard.changeCount` の差分をポーリングで検出する（Maccy 等の業界標準方式）。
//! 変更検知時は Preferences のクリップボード設定（issue #180）を読み込み、
//! フィルタリング・切り詰めを適用したうえで DB に保存する。
//!
//! SAFETY NOTE (NSPasteboard のスレッド安全性):
//! Apple のドキュメント上、NSPasteboard はスレッドセーフであることが保証されていない。
//! 本モジュールの読み取り（ポーリング）は専用のバックグラウンドスレッド1本からのみ行う。
//! 一方 `api::clipboard::copy_text_to_clipboard`（アプリ内コピー）はメインスレッドから
//! `run_on_main_thread` 経由で書き込みを行うため、読み取りスレッドと書き込み（メイン）
//! スレッドの並行アクセスが発生し得る。NSPasteboard はプロセス間で共有されるリソースであり
//! `changeCount` ベースの読み取りは他プロセス（他アプリ）からの書き込みとも常に競合し得る
//! 設計のため、この並行アクセスによってデータ競合が新たに生じることはないと判断している。
//! また各ポーリングイテレーションを `autoreleasepool` で囲み、
//! NSPasteboard から返る autorelease オブジェクトのリークを防いでいる。

use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc, Mutex,
};
use std::thread::{self, JoinHandle};
use std::time::Duration;

use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use tauri::{AppHandle, Manager, Runtime};

use crate::api::clipboard::SELF_COPY_TYPE;
use crate::api::clipboard_settings::{self, ClipboardSettings};
use crate::db::{repository, DbConnection};

const POLL_INTERVAL_MS: u64 = 500;

/// パスワードマネージャ等が「履歴に保存しない」意図を示す UTI（nspasteboard.org 規約）。
const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
/// 自動生成されたコンテンツを示す UTI（nspasteboard.org 規約）。
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// クリップボード変更を監視するモニター。
/// Tauri State として登録し、アプリ終了時（`RunEvent::Exit`）に `stop()` を呼ぶ。
/// `Drop` でも `stop()` するため、State の破棄時にもスレッドは確実に停止する。
pub struct ClipboardMonitor {
    running: Arc<AtomicBool>,
    handle: Mutex<Option<JoinHandle<()>>>,
}

impl ClipboardMonitor {
    pub fn new() -> Self {
        Self {
            running: Arc::new(AtomicBool::new(false)),
            handle: Mutex::new(None),
        }
    }

    /// バックグラウンドポーリングを開始する。2回目以降の呼び出しは no-op。
    pub fn start<R: Runtime>(&self, app: AppHandle<R>) {
        if self.running.swap(true, Ordering::SeqCst) {
            log::warn!("[clipboard_monitor] Already running; start() ignored");
            return;
        }

        let running = Arc::clone(&self.running);
        let handle = thread::spawn(move || {
            log::info!(
                "[clipboard_monitor] Started polling (interval={}ms)",
                POLL_INTERVAL_MS
            );
            let mut last_change_count: isize = -1;

            while running.load(Ordering::SeqCst) {
                unsafe {
                    objc2::rc::autoreleasepool(|_| {
                        let pb = NSPasteboard::generalPasteboard();
                        let count = pb.changeCount();

                        if count != last_change_count {
                            // 起動直後の初回は既存のクリップボード内容を取り込まない
                            if last_change_count != -1 {
                                on_clipboard_changed(&app, &pb);
                            }
                            last_change_count = count;
                        }
                    });
                }
                thread::sleep(Duration::from_millis(POLL_INTERVAL_MS));
            }

            log::info!("[clipboard_monitor] Stopped polling");
        });

        if let Ok(mut guard) = self.handle.lock() {
            *guard = Some(handle);
        }
    }

    /// ポーリングスレッドを停止して終了を待つ（グレースフルシャットダウン）。
    pub fn stop(&self) {
        if !self.running.swap(false, Ordering::SeqCst) {
            return;
        }
        if let Ok(mut guard) = self.handle.lock() {
            if let Some(handle) = guard.take() {
                if handle.join().is_err() {
                    log::error!("[clipboard_monitor] Polling thread panicked");
                }
            }
        }
    }
}

impl Default for ClipboardMonitor {
    fn default() -> Self {
        Self::new()
    }
}

impl Drop for ClipboardMonitor {
    fn drop(&mut self) {
        self.stop();
    }
}

/// changeCount の増加を検知したときに呼ばれる。
/// NSPasteboard からテキストを読み取り、設定に基づくフィルタを適用して保存する。
/// NOTE: クリップボード内容はセキュリティ上ログに出力しない（文字数のみ記録する）。
fn on_clipboard_changed<R: Runtime>(app: &AppHandle<R>, pb: &NSPasteboard) {
    let settings = match clipboard_settings::get_clipboard_settings(app.clone()) {
        Ok(s) => s,
        Err(e) => {
            log::error!("[clipboard_monitor] Failed to get clipboard settings: {e}");
            return;
        }
    };

    if !settings.monitoring_enabled {
        log::debug!("[clipboard_monitor] Skipped: monitoring is disabled");
        return;
    }

    match skip_reason(pb) {
        Some(SkipReason::Concealed) => {
            log::debug!("[clipboard_monitor] Skipped: concealed type (password manager content)");
            return;
        }
        Some(SkipReason::AutoGenerated) => {
            log::debug!("[clipboard_monitor] Skipped: auto-generated type");
            return;
        }
        Some(SkipReason::SelfCopy) => {
            log::debug!("[clipboard_monitor] Skipped: self copy");
            return;
        }
        None => {}
    }

    let text = unsafe {
        pb.stringForType(NSPasteboardTypeString)
            .map(|s| s.to_string())
    };

    let Some(text) = text else {
        log::debug!("[clipboard_monitor] No text content on pasteboard");
        return;
    };

    match save_clipboard_text(app, &settings, &text) {
        Ok(outcome) => log::debug!("[clipboard_monitor] {outcome:?}"),
        Err(e) => log::error!("[clipboard_monitor] Failed to save clipboard text: {e}"),
    }
}

enum SkipReason {
    Concealed,
    AutoGenerated,
    SelfCopy,
}

/// 履歴に保存すべきでない理由（nspasteboard.org 規約の「保存しない」系タイプ、
/// またはアプリ内コピーを示す自前マーカー）が含まれるかを判定する。
fn skip_reason(pb: &NSPasteboard) -> Option<SkipReason> {
    let types = (unsafe { pb.types() })?;
    for i in 0..types.count() {
        let t_str = types.objectAtIndex(i).to_string();
        if t_str == CONCEALED_TYPE {
            return Some(SkipReason::Concealed);
        }
        if t_str == AUTO_GENERATED_TYPE {
            return Some(SkipReason::AutoGenerated);
        }
        if t_str == SELF_COPY_TYPE {
            return Some(SkipReason::SelfCopy);
        }
    }
    None
}

/// クリップボードテキストの保存結果。
#[derive(Debug, PartialEq)]
pub enum SaveOutcome {
    /// 最小文字数未満のためスキップ（文字数を保持）
    SkippedTooShort(usize),
    /// 保存済み（切り詰め後の文字数を保持）
    Saved { char_count: usize, truncated: bool },
}

/// 設定に基づいてクリップボードテキストを DB に保存する。
///
/// - `min_chars` 未満のテキストは保存しない
/// - `max_chars` を超えるテキストは先頭 `max_chars` 文字に切り詰めて保存する
/// - 直前と同一テキストは保存しない（リポジトリ層の重複排除）
/// - 保存後、`max_items` を超えた古い履歴を削除する
pub fn save_clipboard_text<R: Runtime>(
    app: &AppHandle<R>,
    settings: &ClipboardSettings,
    text: &str,
) -> Result<SaveOutcome, String> {
    let char_count = text.chars().count();
    if char_count < settings.min_chars as usize {
        return Ok(SaveOutcome::SkippedTooShort(char_count));
    }

    let truncated = char_count > settings.max_chars as usize;
    let text_to_save: String = if truncated {
        text.chars().take(settings.max_chars as usize).collect()
    } else {
        text.to_string()
    };

    let db = app.state::<DbConnection>();
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    repository::insert_clipboard_history(&conn, &text_to_save).map_err(|e| e.to_string())?;
    repository::delete_oldest_clipboard_history(&conn, settings.max_items)
        .map_err(|e| e.to_string())?;

    Ok(SaveOutcome::Saved {
        char_count: text_to_save.chars().count(),
        truncated,
    })
}
