name: CI

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  frontend:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

  backend:
    name: Backend Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo fmt check
        run: cd src-tauri && cargo fmt -- --check

      - name: Run cargo build
        run: cd src-tauri && cargo build --verbose

      - name: Run cargo test
        run: cd src-tauri && cargo test --verbose
